Get the per-minute price from Wharton Research Data Services (WRDS). Relevant documentation:

- https://wrds-jupyter.wharton.upenn.edu/user/afeld/lab/tree/wrds-code-samples/taq/python/minute_price.ipynb
- https://wrds-www.wharton.upenn.edu/pages/support/programming-wrds/programming-python/python-from-your-computer/
- https://wrds-www.wharton.upenn.edu/pages/support/programming-wrds/programming-python/querying-wrds-data-python/
- https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/taq/general/wrds-overview-taq/
- https://wrds-www.wharton.upenn.edu/documents/1443/wrds_connection.html

In [1]:
import wrds

conn = wrds.Connection()
conn

Loading library list...
Done

In [2]:
sorted(conn.list_libraries())

['aha_sample',
 'ahasamp',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'bank_all',
 'bank_premium_samp',
 'banksamp',
 'block',
 'block_all',
 'boardex_trial',
 'boardsmp',
 'bvd_amadeus_trial',
 'bvd_bvdbankf_trial',
 'bvd_orbis_trial',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'candid_samp',
 'cboe',
 'cboe_all',
 'cboe_sample',
 'cboesamp',
 'cddsamp',
 'ciq',
 'ciq_capstrct',
 'ciq_common',
 'ciq_keydev',
 'ciq_pplintel',
 'ciq_transcripts',
 'ciqsamp',
 'ciqsamp_capstrct',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_pplintel',
 'ciqsamp_ratings',
 'ciqsamp_transactions',
 'ciqsamp_transcripts',
 'cisdmsmp',
 'columnar',
 'comp',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_filings',
 'comp_global_daily',
 'comp_na_daily_all',
 'comp_segments_hist_daily',
 'compsamp',
 'compsamp_all',
 'compsamp_computext',
 'compsamp_snapshot',
 'compseg',
 'contrib',
 'contrib_bond_dickerson',
 'contrib_bond_firm_link',
 'contrib_ceo_turnover',
 'contrib_char_returns',
 'contrib_corp_fed_litigation',
 'contrib_corporate_bond_returns',
 'contrib_corporate_culture',
 'contrib_general',
 'contrib_global_factor',
 'contrib_intangible_value',
 'contrib_kpss',
 'contrib_liquidity_taq',
 'contrib_liva',
 'contrib_patent_firm_link',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_a_treasuries',
 'crsp_q_mutualfunds',
 'crspsamp',
 'crspsamp_all',
 'crspsamp_mf',
 'csmar',
 'csmar_financial',
 'csmar_funds',
 'csmar_trade',
 'csmsamp_all',
 'dealscan',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'etfg_samp',
 'etfgsamp',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'ff',
 'ff_all',
 'fisd',
 'fisd_common',
 'fisd_fisd',
 'fisd_naic',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftsesamp',
 'ftsesamp_russell_us',
 'gutenberg',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ibessamp_kpi',
 'ifgr',
 'ifgrsamp',
 'ims_obp_trial',
 'imssamp',
 'infasamp',
 'infogroup_business_academic',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'infraclear_samp',
 'insdsamp',
 'iri',
 'iri_all',
 'iss',
 'iss_incentive_lab',
 'iss_incentive_lab_europe',
 'iss_va_mf',
 'iss_va_shareholder',
 'iss_va_vote_us',
 'kpisamp',
 'macrofin',
 'macrofin_comm_trade',
 'markit',
 'markit_cds',
 'mfl',
 'mflinks_all',
 'midas',
 'morningstarsamp_cisdm',
 'mpsych_sample',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'mrktsamp_red',
 'msci_climate_samp',
 'msci_common_samp',
 'msci_esg_samp',
 'mscicoms',
 'mscicsmp',
 'msciesmp',
 'msrb',
 'msrb_all',
 'msrbsamp',
 'msrbsamp_all',
 'omtrial',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'panjiva_samp',
 'phlx',
 'phlx_all',
 'pitchbk',
 'pitchbk_common',
 'pitchbk_companies_deals',
 'pitchbk_fund_returns',
 'pitchbk_investors_funds_lps',
 'pitchbk_other_na',
 'pitchbk_other_row',
 'pitchbk_pe_na',
 'pitchbk_pe_row',
 'pitchbk_people',
 'pitchbk_vc_na',
 'pitchbk_vc_row',
 'pitchsmp',
 'pnjvasmp',
 'preqin',
 'preqin_cashflow',
 'preqin_deals',
 'preqin_gp',
 'preqin_lp',
 'preqin_pe',
 'preqin_vc',
 'preqsamp',
 'preqsamp_all',
 'public',
 'public_all',
 'pwt',
 'pwt_all',
 'ravenpack_trial',
 'reprisk_sample',
 'repsamp',
 'revelio_samp',
 'revsamp',
 'risk',
 'risk_directors',
 'risk_governance',
 'risk_proposals',
 'risksamp',
 'risksamp_all',
 'rpnasamp',
 'rq_all',
 'rstat_samp',
 'rstatsmp',
 'sdc',
 'sdcsamp',
 'secsamp',
 'secsamp_all',
 'shvlsamp',
 'snapsamp',
 'snlsamp',
 'snlsamp_fig',
 'sustainalyticssamp_all',
 'sustsamp',
 'taqm_2007',
 'taqm_2010',
 'taqm_2011',
 'taqm_2012',
 'taqm_2013',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'taqm_2020',
 'taqm_2021',
 'taqm_2022',
 'taqm_2023',
 'taqm_2024',
 'taqm_2025',
 'taqm_2026',
 'taqmsamp',
 'taqmsamp_all',
 'taqmsec',
 'taqsamp',
 'taqsamp_all',
 'tass',
 'tfn',
 'totalq',
 'totalq_all',
 'tr_13f',
 'tr_common',
 'tr_dealscan',
 'tr_ds_comds',
 'tr_ds_econ',
 'tr_ds_equities',
 'tr_ds_fut',
 'tr_esg',
 'tr_ibes',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_sdc_ma',
 'tr_sdc_ni',
 'tr_sdc_samples',
 'tr_tass',
 'tr_worldscope',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trcommon',
 'trcstsmp',
 'trdbdmismp',
 'trdbwbsmp',
 'trdssamp',
 'trdstrm',
 'tresg',
 'tresgsmp',
 'trsamp',
 'trsamp_all',
 'trsamp_db_dmi',
 'trsamp_db_wb',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_esg',
 'trsamp_sdc_ma',
 'trsamp_sdc_ni',
 'trsamp_worldscope',
 'trucost_samp',
 'trws',
 'twoiq_samp',
 'twoiqsmp',
 'wabssamp',
 'wappsamp',
 'wenvsmp',
 'wmfsmp',
 'wrds_abs_samp',
 'wrds_environmental_samp',
 'wrds_insiders_samp',
 'wrds_mutualfund_samp',
 'wrds_sec_search',
 'wrds_shortvolume_samp',
 'wrdsapps',
 'wrdsapps_backtest_basic',
 'wrdsapps_backtest_plus',
 'wrdsapps_bondret',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int',
 'wrdsapps_evtstudy_int_ginsight',
 'wrdsapps_evtstudy_lr',
 'wrdsapps_evtstudy_lr_ciq',
 'wrdsapps_evtstudy_us',
 'wrdsapps_finratio',
 'wrdsapps_finratio_ccm',
 'wrdsapps_finratio_ibes',
 'wrdsapps_finratio_ibes_ccm',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_link_crsp_bond',
 'wrdsapps_link_crsp_factset',
 'wrdsapps_link_crsp_ibes',
 'wrdsapps_link_crsp_taq',
 'wrdsapps_link_crsp_taqm',
 'wrdsapps_link_datastream_wscope',
 'wrdsapps_link_dealscan_wscope',
 'wrdsapps_link_supplychain',
 'wrdsapps_patents',
 'wrdsapps_plink_exec_ciq',
 'wrdsapps_plink_exec_trinsider',
 'wrdsapps_plink_trinsider_ciq',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdssec',
 'wrdssec_all',
 'wrdssec_bow',
 'wrdssec_common',
 'wrdssec_midas',
 'wrdssec_secsa',
 'zacksamp',
 'zacksamp_all']

In [3]:
LIBRARY = "taqm_2024"

conn.list_tables(LIBRARY)

['complete_nbbo_2024',
 'complete_nbbo_20240102',
 'complete_nbbo_20240103',
 'complete_nbbo_20240104',
 'complete_nbbo_20240105',
 'complete_nbbo_20240108',
 'complete_nbbo_20240109',
 'complete_nbbo_20240110',
 'complete_nbbo_20240111',
 'complete_nbbo_20240112',
 'complete_nbbo_20240116',
 'complete_nbbo_20240117',
 'complete_nbbo_20240118',
 'complete_nbbo_20240119',
 'complete_nbbo_20240122',
 'complete_nbbo_20240123',
 'complete_nbbo_20240124',
 'complete_nbbo_20240125',
 'complete_nbbo_20240126',
 'complete_nbbo_20240129',
 'complete_nbbo_20240130',
 'complete_nbbo_20240131',
 'complete_nbbo_20240201',
 'complete_nbbo_20240202',
 'complete_nbbo_20240205',
 'complete_nbbo_20240206',
 'complete_nbbo_20240207',
 'complete_nbbo_20240208',
 'complete_nbbo_20240209',
 'complete_nbbo_20240212',
 'complete_nbbo_20240213',
 'complete_nbbo_20240214',
 'complete_nbbo_20240215',
 'complete_nbbo_20240216',
 'complete_nbbo_20240220',
 'complete_nbbo_20240221',
 'complete_nbbo_20240222',
 'complete_nbbo_20240223',
 'complete_nbbo_20240226',
 'complete_nbbo_20240227',
 'complete_nbbo_20240228',
 'complete_nbbo_20240229',
 'complete_nbbo_20240301',
 'complete_nbbo_20240304',
 'complete_nbbo_20240305',
 'complete_nbbo_20240306',
 'complete_nbbo_20240307',
 'complete_nbbo_20240308',
 'complete_nbbo_20240311',
 'complete_nbbo_20240312',
 'complete_nbbo_20240313',
 'complete_nbbo_20240314',
 'complete_nbbo_20240315',
 'complete_nbbo_20240318',
 'complete_nbbo_20240319',
 'complete_nbbo_20240320',
 'complete_nbbo_20240321',
 'complete_nbbo_20240322',
 'complete_nbbo_20240325',
 'complete_nbbo_20240326',
 'complete_nbbo_20240327',
 'complete_nbbo_20240328',
 'complete_nbbo_20240401',
 'complete_nbbo_20240402',
 'complete_nbbo_20240403',
 'complete_nbbo_20240404',
 'complete_nbbo_20240405',
 'complete_nbbo_20240408',
 'complete_nbbo_20240409',
 'complete_nbbo_20240410',
 'complete_nbbo_20240411',
 'complete_nbbo_20240412',
 'complete_nbbo_20240415',
 'complete_nbbo_20240416',
 'complete_nbbo_20240417',
 'complete_nbbo_20240418',
 'complete_nbbo_20240419',
 'complete_nbbo_20240422',
 'complete_nbbo_20240423',
 'complete_nbbo_20240424',
 'complete_nbbo_20240425',
 'complete_nbbo_20240426',
 'complete_nbbo_20240429',
 'complete_nbbo_20240430',
 'complete_nbbo_20240501',
 'complete_nbbo_20240502',
 'complete_nbbo_20240503',
 'complete_nbbo_20240506',
 'complete_nbbo_20240507',
 'complete_nbbo_20240508',
 'complete_nbbo_20240509',
 'complete_nbbo_20240510',
 'complete_nbbo_20240513',
 'complete_nbbo_20240514',
 'complete_nbbo_20240515',
 'complete_nbbo_20240516',
 'complete_nbbo_20240517',
 'complete_nbbo_20240520',
 'complete_nbbo_20240521',
 'complete_nbbo_20240522',
 'complete_nbbo_20240523',
 'complete_nbbo_20240524',
 'complete_nbbo_20240528',
 'complete_nbbo_20240529',
 'complete_nbbo_20240530',
 'complete_nbbo_20240531',
 'complete_nbbo_20240603',
 'complete_nbbo_20240604',
 'complete_nbbo_20240605',
 'complete_nbbo_20240606',
 'complete_nbbo_20240607',
 'complete_nbbo_20240610',
 'complete_nbbo_20240611',
 'complete_nbbo_20240612',
 'complete_nbbo_20240613',
 'complete_nbbo_20240614',
 'complete_nbbo_20240617',
 'complete_nbbo_20240618',
 'complete_nbbo_20240620',
 'complete_nbbo_20240621',
 'complete_nbbo_20240624',
 'complete_nbbo_20240625',
 'complete_nbbo_20240626',
 'complete_nbbo_20240627',
 'complete_nbbo_20240628',
 'complete_nbbo_20240701',
 'complete_nbbo_20240702',
 'complete_nbbo_20240703',
 'complete_nbbo_20240705',
 'complete_nbbo_20240708',
 'complete_nbbo_20240709',
 'complete_nbbo_20240710',
 'complete_nbbo_20240711',
 'complete_nbbo_20240712',
 'complete_nbbo_20240715',
 'complete_nbbo_20240716',
 'complete_nbbo_20240717',
 'complete_nbbo_20240718',
 'complete_nbbo_20240719',
 'complete_nbbo_20240722',
 'complete_nbbo_20240723',
 'complete_nbbo_20240724',
 'complete_nbbo_20240725',
 'complete_nbbo_20240726',
 'complete_nbbo_20240729',
 'complete_nbbo_20240730',
 'complete_nbbo_20240731',
 'complete_nbbo_20240801',
 'complete_nbbo_20240802',
 'complete_nbbo_20240805',
 'complete_nbbo_20240806',
 'complete_nbbo_20240807',
 'complete_nbbo_20240808',
 'complete_nbbo_20240809',
 'complete_nbbo_20240812',
 'complete_nbbo_20240813',
 'complete_nbbo_20240814',
 'complete_nbbo_20240815',
 'complete_nbbo_20240816',
 'complete_nbbo_20240819',
 'complete_nbbo_20240820',
 'complete_nbbo_20240821',
 'complete_nbbo_20240822',
 'complete_nbbo_20240823',
 'complete_nbbo_20240826',
 'complete_nbbo_20240827',
 'complete_nbbo_20240828',
 'complete_nbbo_20240829',
 'complete_nbbo_20240830',
 'complete_nbbo_20240903',
 'complete_nbbo_20240904',
 'complete_nbbo_20240905',
 'complete_nbbo_20240906',
 'complete_nbbo_20240909',
 'complete_nbbo_20240910',
 'complete_nbbo_20240911',
 'complete_nbbo_20240912',
 'complete_nbbo_20240913',
 'complete_nbbo_20240916',
 'complete_nbbo_20240917',
 'complete_nbbo_20240918',
 'complete_nbbo_20240919',
 'complete_nbbo_20240920',
 'complete_nbbo_20240923',
 'complete_nbbo_20240924',
 'complete_nbbo_20240925',
 'complete_nbbo_20240926',
 'complete_nbbo_20240927',
 'complete_nbbo_20240930',
 'complete_nbbo_20241001',
 'complete_nbbo_20241002',
 'complete_nbbo_20241003',
 'complete_nbbo_20241004',
 'complete_nbbo_20241007',
 'complete_nbbo_20241008',
 'complete_nbbo_20241009',
 'complete_nbbo_20241010',
 'complete_nbbo_20241011',
 'complete_nbbo_20241014',
 'complete_nbbo_20241015',
 'complete_nbbo_20241016',
 'complete_nbbo_20241017',
 'complete_nbbo_20241018',
 'complete_nbbo_20241021',
 'complete_nbbo_20241022',
 'complete_nbbo_20241023',
 'complete_nbbo_20241024',
 'complete_nbbo_20241025',
 'complete_nbbo_20241028',
 'complete_nbbo_20241029',
 'complete_nbbo_20241030',
 'complete_nbbo_20241031',
 'complete_nbbo_20241101',
 'complete_nbbo_20241104',
 'complete_nbbo_20241105',
 'complete_nbbo_20241106',
 'complete_nbbo_20241107',
 'complete_nbbo_20241108',
 'complete_nbbo_20241111',
 'complete_nbbo_20241112',
 'complete_nbbo_20241113',
 'complete_nbbo_20241114',
 'complete_nbbo_20241115',
 'complete_nbbo_20241118',
 'complete_nbbo_20241119',
 'complete_nbbo_20241120',
 'complete_nbbo_20241121',
 'complete_nbbo_20241122',
 'complete_nbbo_20241125',
 'complete_nbbo_20241126',
 'complete_nbbo_20241127',
 'complete_nbbo_20241129',
 'complete_nbbo_20241202',
 'complete_nbbo_20241203',
 'complete_nbbo_20241204',
 'complete_nbbo_20241205',
 'complete_nbbo_20241206',
 'complete_nbbo_20241209',
 'complete_nbbo_20241210',
 'complete_nbbo_20241211',
 'complete_nbbo_20241212',
 'complete_nbbo_20241213',
 'complete_nbbo_20241216',
 'complete_nbbo_20241217',
 'complete_nbbo_20241218',
 'complete_nbbo_20241219',
 'complete_nbbo_20241220',
 'complete_nbbo_20241223',
 'complete_nbbo_20241224',
 'complete_nbbo_20241226',
 'complete_nbbo_20241227',
 'complete_nbbo_20241230',
 'complete_nbbo_20241231',
 'cqm_2024',
 'cqm_20240102',
 'cqm_20240103',
 'cqm_20240104',
 'cqm_20240105',
 'cqm_20240108',
 'cqm_20240109',
 'cqm_20240110',
 'cqm_20240111',
 'cqm_20240112',
 'cqm_20240116',
 'cqm_20240117',
 'cqm_20240118',
 'cqm_20240119',
 'cqm_20240122',
 'cqm_20240123',
 'cqm_20240124',
 'cqm_20240125',
 'cqm_20240126',
 'cqm_20240129',
 'cqm_20240130',
 'cqm_20240131',
 'cqm_20240201',
 'cqm_20240202',
 'cqm_20240205',
 'cqm_20240206',
 'cqm_20240207',
 'cqm_20240208',
 'cqm_20240209',
 'cqm_20240212',
 'cqm_20240213',
 'cqm_20240214',
 'cqm_20240215',
 'cqm_20240216',
 'cqm_20240220',
 'cqm_20240221',
 'cqm_20240222',
 'cqm_20240223',
 'cqm_20240226',
 'cqm_20240227',
 'cqm_20240228',
 'cqm_20240229',
 'cqm_20240301',
 'cqm_20240304',
 'cqm_20240305',
 'cqm_20240306',
 'cqm_20240307',
 'cqm_20240308',
 'cqm_20240311',
 'cqm_20240312',
 'cqm_20240313',
 'cqm_20240314',
 'cqm_20240315',
 'cqm_20240318',
 'cqm_20240319',
 'cqm_20240320',
 'cqm_20240321',
 'cqm_20240322',
 'cqm_20240325',
 'cqm_20240326',
 'cqm_20240327',
 'cqm_20240328',
 'cqm_20240401',
 'cqm_20240402',
 'cqm_20240403',
 'cqm_20240404',
 'cqm_20240405',
 'cqm_20240408',
 'cqm_20240409',
 'cqm_20240410',
 'cqm_20240411',
 'cqm_20240412',
 'cqm_20240415',
 'cqm_20240416',
 'cqm_20240417',
 'cqm_20240418',
 'cqm_20240419',
 'cqm_20240422',
 'cqm_20240423',
 'cqm_20240424',
 'cqm_20240425',
 'cqm_20240426',
 'cqm_20240429',
 'cqm_20240430',
 'cqm_20240501',
 'cqm_20240502',
 'cqm_20240503',
 'cqm_20240506',
 'cqm_20240507',
 'cqm_20240508',
 'cqm_20240509',
 'cqm_20240510',
 'cqm_20240513',
 'cqm_20240514',
 'cqm_20240515',
 'cqm_20240516',
 'cqm_20240517',
 'cqm_20240520',
 'cqm_20240521',
 'cqm_20240522',
 'cqm_20240523',
 'cqm_20240524',
 'cqm_20240528',
 'cqm_20240529',
 'cqm_20240530',
 'cqm_20240531',
 'cqm_20240603',
 'cqm_20240604',
 'cqm_20240605',
 'cqm_20240606',
 'cqm_20240607',
 'cqm_20240610',
 'cqm_20240611',
 'cqm_20240612',
 'cqm_20240613',
 'cqm_20240614',
 'cqm_20240617',
 'cqm_20240618',
 'cqm_20240620',
 'cqm_20240621',
 'cqm_20240624',
 'cqm_20240625',
 'cqm_20240626',
 'cqm_20240627',
 'cqm_20240628',
 'cqm_20240701',
 'cqm_20240702',
 'cqm_20240703',
 'cqm_20240705',
 'cqm_20240708',
 'cqm_20240709',
 'cqm_20240710',
 'cqm_20240711',
 'cqm_20240712',
 'cqm_20240715',
 'cqm_20240716',
 'cqm_20240717',
 'cqm_20240718',
 'cqm_20240719',
 'cqm_20240722',
 'cqm_20240723',
 'cqm_20240724',
 'cqm_20240725',
 'cqm_20240726',
 'cqm_20240729',
 'cqm_20240730',
 'cqm_20240731',
 'cqm_20240801',
 'cqm_20240802',
 'cqm_20240805',
 'cqm_20240806',
 'cqm_20240807',
 'cqm_20240808',
 'cqm_20240809',
 'cqm_20240812',
 'cqm_20240813',
 'cqm_20240814',
 'cqm_20240815',
 'cqm_20240816',
 'cqm_20240819',
 'cqm_20240820',
 'cqm_20240821',
 'cqm_20240822',
 'cqm_20240823',
 'cqm_20240826',
 'cqm_20240827',
 'cqm_20240828',
 'cqm_20240829',
 'cqm_20240830',
 'cqm_20240903',
 'cqm_20240904',
 'cqm_20240905',
 'cqm_20240906',
 'cqm_20240909',
 'cqm_20240910',
 'cqm_20240911',
 'cqm_20240912',
 'cqm_20240913',
 'cqm_20240916',
 'cqm_20240917',
 'cqm_20240918',
 'cqm_20240919',
 'cqm_20240920',
 'cqm_20240923',
 'cqm_20240924',
 'cqm_20240925',
 'cqm_20240926',
 'cqm_20240927',
 'cqm_20240930',
 'cqm_20241001',
 'cqm_20241002',
 'cqm_20241003',
 'cqm_20241004',
 'cqm_20241007',
 'cqm_20241008',
 'cqm_20241009',
 'cqm_20241010',
 'cqm_20241011',
 'cqm_20241014',
 'cqm_20241015',
 'cqm_20241016',
 'cqm_20241017',
 'cqm_20241018',
 'cqm_20241021',
 'cqm_20241022',
 'cqm_20241023',
 'cqm_20241024',
 'cqm_20241025',
 'cqm_20241028',
 'cqm_20241029',
 'cqm_20241030',
 'cqm_20241031',
 'cqm_20241101',
 'cqm_20241104',
 'cqm_20241105',
 'cqm_20241106',
 'cqm_20241107',
 'cqm_20241108',
 'cqm_20241111',
 'cqm_20241112',
 'cqm_20241113',
 'cqm_20241114',
 'cqm_20241115',
 'cqm_20241118',
 'cqm_20241119',
 'cqm_20241120',
 'cqm_20241121',
 'cqm_20241122',
 'cqm_20241125',
 'cqm_20241126',
 'cqm_20241127',
 'cqm_20241129',
 'cqm_20241202',
 'cqm_20241203',
 'cqm_20241204',
 'cqm_20241205',
 'cqm_20241206',
 'cqm_20241209',
 'cqm_20241210',
 'cqm_20241211',
 'cqm_20241212',
 'cqm_20241213',
 'cqm_20241216',
 'cqm_20241217',
 'cqm_20241218',
 'cqm_20241219',
 'cqm_20241220',
 'cqm_20241223',
 'cqm_20241224',
 'cqm_20241226',
 'cqm_20241227',
 'cqm_20241230',
 'cqm_20241231',
 'ctm_2024',
 'ctm_20240102',
 'ctm_20240103',
 'ctm_20240104',
 'ctm_20240105',
 'ctm_20240108',
 'ctm_20240109',
 'ctm_20240110',
 'ctm_20240111',
 'ctm_20240112',
 'ctm_20240116',
 'ctm_20240117',
 'ctm_20240118',
 'ctm_20240119',
 'ctm_20240122',
 'ctm_20240123',
 'ctm_20240124',
 'ctm_20240125',
 'ctm_20240126',
 'ctm_20240129',
 'ctm_20240130',
 'ctm_20240131',
 'ctm_20240201',
 'ctm_20240202',
 'ctm_20240205',
 'ctm_20240206',
 'ctm_20240207',
 'ctm_20240208',
 'ctm_20240209',
 'ctm_20240212',
 'ctm_20240213',
 'ctm_20240214',
 'ctm_20240215',
 'ctm_20240216',
 'ctm_20240220',
 'ctm_20240221',
 'ctm_20240222',
 'ctm_20240223',
 'ctm_20240226',
 'ctm_20240227',
 'ctm_20240228',
 'ctm_20240229',
 'ctm_20240301',
 'ctm_20240304',
 'ctm_20240305',
 'ctm_20240306',
 'ctm_20240307',
 'ctm_20240308',
 'ctm_20240311',
 'ctm_20240312',
 'ctm_20240313',
 'ctm_20240314',
 'ctm_20240315',
 'ctm_20240318',
 'ctm_20240319',
 'ctm_20240320',
 'ctm_20240321',
 'ctm_20240322',
 'ctm_20240325',
 'ctm_20240326',
 'ctm_20240327',
 'ctm_20240328',
 'ctm_20240401',
 'ctm_20240402',
 'ctm_20240403',
 'ctm_20240404',
 'ctm_20240405',
 'ctm_20240408',
 'ctm_20240409',
 'ctm_20240410',
 'ctm_20240411',
 'ctm_20240412',
 'ctm_20240415',
 'ctm_20240416',
 'ctm_20240417',
 'ctm_20240418',
 'ctm_20240419',
 'ctm_20240422',
 'ctm_20240423',
 'ctm_20240424',
 'ctm_20240425',
 'ctm_20240426',
 'ctm_20240429',
 'ctm_20240430',
 'ctm_20240501',
 'ctm_20240502',
 'ctm_20240503',
 'ctm_20240506',
 'ctm_20240507',
 'ctm_20240508',
 'ctm_20240509',
 'ctm_20240510',
 'ctm_20240513',
 'ctm_20240514',
 'ctm_20240515',
 'ctm_20240516',
 'ctm_20240517',
 'ctm_20240520',
 'ctm_20240521',
 'ctm_20240522',
 'ctm_20240523',
 'ctm_20240524',
 'ctm_20240528',
 'ctm_20240529',
 'ctm_20240530',
 'ctm_20240531',
 'ctm_20240603',
 'ctm_20240604',
 'ctm_20240605',
 'ctm_20240606',
 'ctm_20240607',
 'ctm_20240610',
 'ctm_20240611',
 'ctm_20240612',
 'ctm_20240613',
 'ctm_20240614',
 'ctm_20240617',
 'ctm_20240618',
 'ctm_20240620',
 'ctm_20240621',
 'ctm_20240624',
 'ctm_20240625',
 'ctm_20240626',
 'ctm_20240627',
 'ctm_20240628',
 'ctm_20240701',
 'ctm_20240702',
 'ctm_20240703',
 'ctm_20240705',
 'ctm_20240708',
 'ctm_20240709',
 'ctm_20240710',
 'ctm_20240711',
 'ctm_20240712',
 'ctm_20240715',
 'ctm_20240716',
 'ctm_20240717',
 'ctm_20240718',
 'ctm_20240719',
 'ctm_20240722',
 'ctm_20240723',
 'ctm_20240724',
 'ctm_20240725',
 'ctm_20240726',
 'ctm_20240729',
 'ctm_20240730',
 'ctm_20240731',
 'ctm_20240801',
 'ctm_20240802',
 'ctm_20240805',
 'ctm_20240806',
 'ctm_20240807',
 'ctm_20240808',
 'ctm_20240809',
 'ctm_20240812',
 'ctm_20240813',
 'ctm_20240814',
 'ctm_20240815',
 'ctm_20240816',
 'ctm_20240819',
 'ctm_20240820',
 'ctm_20240821',
 'ctm_20240822',
 'ctm_20240823',
 'ctm_20240826',
 'ctm_20240827',
 'ctm_20240828',
 'ctm_20240829',
 'ctm_20240830',
 'ctm_20240903',
 'ctm_20240904',
 'ctm_20240905',
 'ctm_20240906',
 'ctm_20240909',
 'ctm_20240910',
 'ctm_20240911',
 'ctm_20240912',
 'ctm_20240913',
 'ctm_20240916',
 'ctm_20240917',
 'ctm_20240918',
 'ctm_20240919',
 'ctm_20240920',
 'ctm_20240923',
 'ctm_20240924',
 'ctm_20240925',
 'ctm_20240926',
 'ctm_20240927',
 'ctm_20240930',
 'ctm_20241001',
 'ctm_20241002',
 'ctm_20241003',
 'ctm_20241004',
 'ctm_20241007',
 'ctm_20241008',
 'ctm_20241009',
 'ctm_20241010',
 'ctm_20241011',
 'ctm_20241014',
 'ctm_20241015',
 'ctm_20241016',
 'ctm_20241017',
 'ctm_20241018',
 'ctm_20241021',
 'ctm_20241022',
 'ctm_20241023',
 'ctm_20241024',
 'ctm_20241025',
 'ctm_20241028',
 'ctm_20241029',
 'ctm_20241030',
 'ctm_20241031',
 'ctm_20241101',
 'ctm_20241104',
 'ctm_20241105',
 'ctm_20241106',
 'ctm_20241107',
 'ctm_20241108',
 'ctm_20241111',
 'ctm_20241112',
 'ctm_20241113',
 'ctm_20241114',
 'ctm_20241115',
 'ctm_20241118',
 'ctm_20241119',
 'ctm_20241120',
 'ctm_20241121',
 'ctm_20241122',
 'ctm_20241125',
 'ctm_20241126',
 'ctm_20241127',
 'ctm_20241129',
 'ctm_20241202',
 'ctm_20241203',
 'ctm_20241204',
 'ctm_20241205',
 'ctm_20241206',
 'ctm_20241209',
 'ctm_20241210',
 'ctm_20241211',
 'ctm_20241212',
 'ctm_20241213',
 'ctm_20241216',
 'ctm_20241217',
 'ctm_20241218',
 'ctm_20241219',
 'ctm_20241220',
 'ctm_20241223',
 'ctm_20241224',
 'ctm_20241226',
 'ctm_20241227',
 'ctm_20241230',
 'ctm_20241231',
 'luld_cqm_2024',
 'luld_cqm_20240102',
 'luld_cqm_20240103',
 'luld_cqm_20240104',
 'luld_cqm_20240105',
 'luld_cqm_20240108',
 'luld_cqm_20240109',
 'luld_cqm_20240110',
 'luld_cqm_20240111',
 'luld_cqm_20240112',
 'luld_cqm_20240116',
 'luld_cqm_20240117',
 'luld_cqm_20240118',
 'luld_cqm_20240119',
 'luld_cqm_20240122',
 'luld_cqm_20240123',
 'luld_cqm_20240124',
 'luld_cqm_20240125',
 'luld_cqm_20240126',
 'luld_cqm_20240129',
 'luld_cqm_20240130',
 'luld_cqm_20240131',
 'luld_cqm_20240201',
 'luld_cqm_20240202',
 'luld_cqm_20240205',
 'luld_cqm_20240206',
 'luld_cqm_20240207',
 'luld_cqm_20240208',
 'luld_cqm_20240209',
 'luld_cqm_20240212',
 'luld_cqm_20240213',
 'luld_cqm_20240214',
 'luld_cqm_20240215',
 'luld_cqm_20240216',
 'luld_cqm_20240220',
 'luld_cqm_20240221',
 'luld_cqm_20240222',
 'luld_cqm_20240223',
 'luld_cqm_20240226',
 'luld_cqm_20240227',
 'luld_cqm_20240228',
 'luld_cqm_20240229',
 'luld_cqm_20240301',
 'luld_cqm_20240304',
 'luld_cqm_20240305',
 'luld_cqm_20240306',
 'luld_cqm_20240307',
 'luld_cqm_20240308',
 'luld_cqm_20240311',
 'luld_cqm_20240312',
 'luld_cqm_20240313',
 'luld_cqm_20240314',
 'luld_cqm_20240315',
 'luld_cqm_20240318',
 'luld_cqm_20240319',
 'luld_cqm_20240320',
 'luld_cqm_20240321',
 'luld_cqm_20240322',
 'luld_cqm_20240325',
 'luld_cqm_20240326',
 'luld_cqm_20240327',
 'luld_cqm_20240328',
 'luld_cqm_20240401',
 'luld_cqm_20240402',
 'luld_cqm_20240403',
 'luld_cqm_20240404',
 'luld_cqm_20240405',
 'luld_cqm_20240408',
 'luld_cqm_20240409',
 'luld_cqm_20240410',
 'luld_cqm_20240411',
 'luld_cqm_20240412',
 'luld_cqm_20240415',
 'luld_cqm_20240416',
 'luld_cqm_20240417',
 'luld_cqm_20240418',
 'luld_cqm_20240419',
 'luld_cqm_20240422',
 'luld_cqm_20240423',
 'luld_cqm_20240424',
 'luld_cqm_20240425',
 'luld_cqm_20240426',
 'luld_cqm_20240429',
 'luld_cqm_20240430',
 'luld_cqm_20240501',
 'luld_cqm_20240502',
 'luld_cqm_20240503',
 'luld_cqm_20240506',
 'luld_cqm_20240507',
 'luld_cqm_20240508',
 'luld_cqm_20240509',
 'luld_cqm_20240510',
 'luld_cqm_20240513',
 'luld_cqm_20240514',
 'luld_cqm_20240515',
 'luld_cqm_20240516',
 'luld_cqm_20240517',
 'luld_cqm_20240520',
 'luld_cqm_20240521',
 'luld_cqm_20240522',
 'luld_cqm_20240523',
 'luld_cqm_20240524',
 'luld_cqm_20240528',
 'luld_cqm_20240529',
 'luld_cqm_20240530',
 'luld_cqm_20240531',
 'luld_cqm_20240603',
 'luld_cqm_20240604',
 'luld_cqm_20240605',
 'luld_cqm_20240606',
 'luld_cqm_20240607',
 'luld_cqm_20240610',
 'luld_cqm_20240611',
 'luld_cqm_20240612',
 'luld_cqm_20240613',
 'luld_cqm_20240614',
 'luld_cqm_20240617',
 'luld_cqm_20240618',
 'luld_cqm_20240620',
 'luld_cqm_20240621',
 'luld_cqm_20240624',
 'luld_cqm_20240625',
 'luld_cqm_20240626',
 'luld_cqm_20240627',
 'luld_cqm_20240628',
 'luld_cqm_20240701',
 'luld_cqm_20240702',
 'luld_cqm_20240703',
 'luld_cqm_20240705',
 'luld_cqm_20240708',
 'luld_cqm_20240709',
 'luld_cqm_20240710',
 'luld_cqm_20240711',
 'luld_cqm_20240712',
 'luld_cqm_20240715',
 'luld_cqm_20240716',
 'luld_cqm_20240717',
 'luld_cqm_20240718',
 'luld_cqm_20240719',
 'luld_cqm_20240722',
 'luld_cqm_20240723',
 'luld_cqm_20240724',
 'luld_cqm_20240725',
 'luld_cqm_20240726',
 'luld_cqm_20240729',
 'luld_cqm_20240730',
 'luld_cqm_20240731',
 'luld_cqm_20240801',
 'luld_cqm_20240802',
 'luld_cqm_20240805',
 'luld_cqm_20240806',
 'luld_cqm_20240807',
 'luld_cqm_20240808',
 'luld_cqm_20240809',
 'luld_cqm_20240812',
 'luld_cqm_20240813',
 'luld_cqm_20240814',
 'luld_cqm_20240815',
 'luld_cqm_20240816',
 'luld_cqm_20240819',
 'luld_cqm_20240820',
 'luld_cqm_20240821',
 'luld_cqm_20240822',
 'luld_cqm_20240823',
 'luld_cqm_20240826',
 'luld_cqm_20240827',
 'luld_cqm_20240828',
 'luld_cqm_20240829',
 'luld_cqm_20240830',
 'luld_cqm_20240903',
 'luld_cqm_20240904',
 'luld_cqm_20240905',
 'luld_cqm_20240906',
 'luld_cqm_20240909',
 'luld_cqm_20240910',
 'luld_cqm_20240911',
 'luld_cqm_20240912',
 'luld_cqm_20240913',
 'luld_cqm_20240916',
 'luld_cqm_20240917',
 'luld_cqm_20240918',
 'luld_cqm_20240919',
 'luld_cqm_20240920',
 'luld_cqm_20240923',
 'luld_cqm_20240924',
 'luld_cqm_20240925',
 'luld_cqm_20240926',
 'luld_cqm_20240927',
 'luld_cqm_20240930',
 'luld_cqm_20241001',
 'luld_cqm_20241002',
 'luld_cqm_20241003',
 'luld_cqm_20241004',
 'luld_cqm_20241007',
 'luld_cqm_20241008',
 'luld_cqm_20241009',
 'luld_cqm_20241010',
 'luld_cqm_20241011',
 'luld_cqm_20241014',
 'luld_cqm_20241015',
 'luld_cqm_20241016',
 'luld_cqm_20241017',
 'luld_cqm_20241018',
 'luld_cqm_20241021',
 'luld_cqm_20241022',
 'luld_cqm_20241023',
 'luld_cqm_20241024',
 'luld_cqm_20241025',

In [4]:
conn.describe_table(LIBRARY, "ctm_20241203")

Approximately 80411896 rows in taqm_2024.ctm_20241203.

              name  nullable        type comment
0             date     False        DATE    None
1           time_m     False        TIME    None
2      time_m_nano      True    SMALLINT    None
3               ex      True  VARCHAR(1)    None
4         sym_root     False        TEXT    None
5       sym_suffix      True        TEXT    None
6         tr_scond      True  VARCHAR(4)    None
7             size      True     INTEGER    None
8            price      True     NUMERIC    None
9      tr_stop_ind      True  VARCHAR(1)    None
10         tr_corr      True  VARCHAR(2)    None
11       tr_seqnum      True      BIGINT    None
12           tr_id      True        TEXT    None
13       tr_source      True  VARCHAR(1)    None
14           tr_rf      True  VARCHAR(1)    None
15       part_time      True        TIME    None
16  part_time_nano      True    SMALLINT    None
17        trf_time      True        TIME    None
18   trf_time_nano      True    SMALLINT    None
19         tte_ind      True  VARCHAR(1)    None

In [5]:
df = conn.raw_sql(f"""
WITH milli AS (
    SELECT * FROM {LIBRARY}.ctm_20241203
    UNION ALL
    SELECT * FROM {LIBRARY}.ctm_20241204
)
SELECT
    date_bin('1 minute', date + time_m, TIMESTAMP '2024-12-03') AS ts_minute,
    AVG(price) AS average_price
FROM milli
WHERE sym_root = 'UNH'
GROUP BY ts_minute
ORDER BY ts_minute
""")

df

               ts_minute  average_price
0    2024-12-03 04:18:00     608.996667
1    2024-12-03 04:31:00         608.99
2    2024-12-03 05:07:00         608.52
3    2024-12-03 05:30:00         608.31
4    2024-12-03 06:42:00         608.51
...                  ...            ...
1199 2024-12-04 19:53:00         610.08
1200 2024-12-04 19:54:00         610.08
1201 2024-12-04 19:55:00          612.9
1202 2024-12-04 19:58:00         611.84
1203 2024-12-04 19:59:00          610.0

[1204 rows x 2 columns]

In [6]:
df.to_csv("minute_price.csv", index=False)