- https://www.dailymail.com/yourmoney/consumer/article-14158085/unitedhealthcare-stock-price-jumps-ceo-brian-thompson-shot-dead.html
- https://www.unitedhealthgroup.com/newsroom/2024/2024-12-3-uhg-business-outlook-investor-conference.html

In [44]:
import pandas as pd

file_path = "OLHCV-1m/xnas-itch-20241201-20241231.ohlcv-1m.csv.zst"
df = pd.read_csv(
    file_path,
    compression="zstd",
    parse_dates=["ts_event"],
)
df = df.sort_values("ts_event")

stock_symbol = df["symbol"].iloc[0]

df

,ts_event,rtype,publisher_id,instrument_id,open,high,low,close,volume,symbol
0,2024-12-02 09:39:00+00:00,33,2,16549,615.14,615.14,615.14,615.14,25,UNH
1,2024-12-02 11:14:00+00:00,33,2,16549,613.47,613.47,613.47,613.47,1,UNH
2,2024-12-02 11:41:00+00:00,33,2,16549,611.80,613.45,611.80,613.45,8,UNH
3,2024-12-02 13:22:00+00:00,33,2,16549,611.57,611.57,611.57,611.57,1,UNH
4,2024-12-02 13:50:00+00:00,33,2,16549,611.53,611.53,611.53,611.53,10,UNH
...,...,...,...,...,...,...,...,...,...,...
9837,2024-12-30 22:40:00+00:00,33,2,16549,507.55,507.55,507.55,507.55,2,UNH
9838,2024-12-30 22:52:00+00:00,33,2,16549,507.56,507.56,507.56,507.56,3,UNH
9839,2024-12-30 23:04:00+00:00,33,2,16549,507.08,507.08,507.08,507.08,34,UNH
9840,2024-12-30 23:35:00+00:00,33,2,16549,508.25,508.25,508.25,508.25,3,UNH
9841,2024-12-30 23:39:00+00:00,33,2,16549,508.26,508.26,508.26,508.26,5,UNH

In [45]:
df["ts_event_ny"] = df["ts_event"].dt.tz_convert(tz="US/Eastern")

- https://www.unitedhealthgroup.com/newsroom/2024/2024-12-3-uhg-business-outlook-investor-conference.html
- https://www.nasdaq.com/press-release/unitedhealth-group-updates-business-outlook-ahead-investor-conference-2024-12-03
- https://web.archive.org/web/20240000000000*/https://www.unitedhealthgroup.com/newsroom/2024/2024-12-3-uhg-business-outlook-investor-conference.html
- https://news.sky.com/story/what-we-know-about-new-york-city-shooting-of-unitedhealthcare-boss-brian-thompson-13267264
- https://edition.cnn.com/us/live-news/unitedhealthcare-brian-thompson-death-12-04-24/#cm4a356lf00003b6m6nr979mg

In [46]:
vlines = [
    {
        "time": pd.Timestamp("2024-12-03 16:15:00", tz="US/Eastern"),
        "label": "UnitedHealth Group 2025 outlook released",
    },
    {
        "time": pd.Timestamp("2024-12-04 06:45:00", tz="US/Eastern"),
        "label": "Brian Thompson shot",
    },
]

- https://x.com/search?q=breaking%20hilton%20shot%20until%3A2024-12-05%20since%3A2024-12-04%20&src=typed_query&f=top
- https://x.com/fox5ny/status/1864287586723717482
- https://x.com/PIX11News/status/1864306484697321911

In [47]:
news_broke_start_time = pd.Timestamp("2024-12-04 07:36:00", tz="US/Eastern")
news_broke_end_time = pd.Timestamp("2024-12-04 09:00:00", tz="US/Eastern")
news_broke_label = "News of shooting breaking"

In [48]:
time_start = pd.Timestamp("2024-12-03 00:00:00", tz="US/Central")
time_end = pd.Timestamp("2024-12-05 00:00:00", tz="US/Eastern")

df_filtered = df[(df["ts_event_ny"] >= time_start) & (df["ts_event_ny"] <= time_end)]
df_filtered

,ts_event,rtype,publisher_id,instrument_id,open,high,low,close,volume,symbol,ts_event_ny
394,2024-12-03 12:27:00+00:00,33,2,16549,609.59,609.59,609.59,609.59,1000,UNH,2024-12-03 07:27:00-05:00
395,2024-12-03 13:33:00+00:00,33,2,16549,609.59,609.59,609.59,609.59,1,UNH,2024-12-03 08:33:00-05:00
396,2024-12-03 13:53:00+00:00,33,2,16549,609.26,609.26,609.26,609.26,12,UNH,2024-12-03 08:53:00-05:00
397,2024-12-03 13:57:00+00:00,33,2,16549,609.25,609.25,609.25,609.25,4,UNH,2024-12-03 08:57:00-05:00
398,2024-12-03 14:05:00+00:00,33,2,16549,608.96,608.97,608.96,608.97,2,UNH,2024-12-03 09:05:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...
1269,2024-12-04 23:28:00+00:00,33,2,16549,609.56,609.56,609.55,609.55,22,UNH,2024-12-04 18:28:00-05:00
1270,2024-12-04 23:35:00+00:00,33,2,16549,609.01,609.01,609.01,609.01,5,UNH,2024-12-04 18:35:00-05:00
1271,2024-12-04 23:39:00+00:00,33,2,16549,609.00,609.00,608.00,608.00,3,UNH,2024-12-04 18:39:00-05:00
1272,2024-12-04 23:47:00+00:00,33,2,16549,611.00,611.00,611.00,611.00,3,UNH,2024-12-04 18:47:00-05:00
1273,2024-12-04 23:49:00+00:00,33,2,16549,610.00,610.00,609.99,609.99,6,UNH,2024-12-04 18:49:00-05:00

https://web.archive.org/web/20240000000000*/https://www.unitedhealthgroup.com/newsroom/2024/2024-12-3-uhg-business-outlook-investor-conference.html

In [49]:
import plotly.express as px

fig = px.line(
    df_filtered,
    x="ts_event_ny",
    y="close",
    title=f"{stock_symbol} Stock Price Over Time",
    labels={
        "ts_event_ny": "Time (US Eastern)",
        "close": "Close Price (USD)",
    },
)

fig.update_traces(mode="lines")

for line in vlines:
    fig.add_vline(
        x=line["time"],
        line_dash="dash",
        line_color="crimson",
        annotation_text=line["label"],
        annotation_position="bottom left",
        annotation_font_color="crimson",
    )

fig.add_vrect(
    x0=news_broke_start_time,
    x1=news_broke_end_time,
    annotation_text=news_broke_label,
    annotation_position="top left",
    fillcolor="crimson",
    opacity=0.25,
    line_width=0,
)

fig.show()